import { useContext } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { StoreContext } from '../context/StoreContext';
const Cart = () => {
  const { cartItems, subtotal, updateQuantity } = useContext(StoreContext); const navigate = useNavigate(); const shipping = subtotal ? 10 : 0;
  return (
    <div className="pt-6 sm:pt-10"><h1 className="text-xl sm:text-2xl">YOUR <span className="font-semibold">CART</span></h1>{cartItems.length === 0 ? <div className="py-20 text-center"><p className="text-gray-500">Your cart is empty.</p><Link className="mt-5 inline-block bg-black px-6 py-3 text-sm text-white" to="/collection">CONTINUE SHOPPING</Link></div> : <div className="mt-6 grid gap-8 lg:mt-8 lg:grid-cols-[1fr_340px] lg:gap-12"><div>{cartItems.map(({ key, product, size, quantity }) => <div key={key} className="flex items-start gap-3 border-t py-4 sm:gap-5 sm:py-5"><img src={product.image[0]} className="h-24 w-20 bg-[#f8f5f2] object-cover sm:h-28 sm:w-24" alt={product.name}/><div className="min-w-0 flex-1"><p className="text-sm sm:text-base">{product.name}</p><div className="mt-2 flex flex-wrap items-center gap-2 text-sm sm:mt-3 sm:gap-5"><span>₹{product.price}</span><span className="border px-2 py-1">Size: {size}</span></div><div className="mt-3 flex items-center gap-2 sm:mt-4"><button onClick={() => updateQuantity(key, quantity - 1)} className="min-h-8 min-w-8 border px-2">−</button><span className="w-6 text-center">{quantity}</span><button onClick={() => updateQuantity(key, quantity + 1)} className="min-h-8 min-w-8 border px-2">+</button><button onClick={() => updateQuantity(key, 0)} className="ml-1 text-xs text-red-600 underline sm:ml-3">Remove</button></div></div><p className="text-sm font-medium sm:text-base">₹{product.price * quantity}</p></div>)}</div><aside className="h-fit bg-gray-50 p-5 sm:p-6"><h2 className="text-xl">CART TOTAL</h2><div className="mt-5 space-y-3 border-y py-4 text-sm"><p className="flex justify-between"><span>Subtotal</span><span>₹{subtotal}</span></p><p className="flex justify-between"><span>Shipping</span><span>₹{shipping}</span></p></div><p className="flex justify-between py-4 font-semibold"><span>Total</span><span>₹{subtotal + shipping}</span></p><button onClick={() => navigate('/place-order')} className="min-h-11 w-full bg-black py-3 text-sm text-white">PROCEED TO CHECKOUT</button></aside></div>}</div>
  )
}
export default Cart
