import { useContext, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { StoreContext } from '../context/StoreContext';
const Login = () => {
  const { authenticate, backendConfigured } = useContext(StoreContext); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [mode, setMode] = useState('login'); const [error, setError] = useState(''); const navigate = useNavigate();
  const submit = async (e) => { e.preventDefault(); setError(''); try { if (backendConfigured) await authenticate(mode, { name, email, password }); else { if (!name && mode === 'register') throw new Error('Enter your name.'); localStorage.setItem('knit-user', JSON.stringify({ name: name || email.split('@')[0], email })); window.location.reload(); } navigate('/'); } catch (err) { setError(err.message); } };
  return (
    <form onSubmit={submit} className="mx-auto my-16 max-w-md border p-8"><h1 className="text-center text-2xl">{mode === 'login' ? 'LOGIN' : 'CREATE'} <span className="font-semibold">ACCOUNT</span></h1><p className="mt-3 text-center text-sm text-gray-500">{backendConfigured ? 'Your account and orders are securely saved.' : 'Backend is not configured yet; this is demo mode.'}</p>{mode === 'register' && <input required value={name} onChange={(e) => setName(e.target.value)} className="mt-7 w-full border p-3" placeholder="Full name" />}<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-3 w-full border p-3" placeholder="Email address" /><input required minLength="8" type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-3 w-full border p-3" placeholder="Password (minimum 8 characters)" />{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<button className="mt-5 w-full bg-black py-3 text-sm text-white">{mode === 'login' ? 'LOGIN' : 'CREATE ACCOUNT'}</button><button type="button" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError(''); }} className="mt-4 w-full text-sm underline">{mode === 'login' ? 'New here? Create an account' : 'Already have an account? Login'}</button></form>
  )
}
export default Login
