import { useContext, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { StoreContext } from '../context/StoreContext';
const PlaceOrder = () => {
  const { cartItems, subtotal, placeOrder, user } = useContext(StoreContext); const navigate = useNavigate(); const [payment, setPayment] = useState('COD');
  const submit = async (e) => { e.preventDefault(); if (!cartItems.length) return navigate('/cart'); const data = Object.fromEntries(new FormData(e.currentTarget)); await placeOrder(data, payment); navigate('/orders'); };
  return (
    <form onSubmit={submit} className="grid gap-12 pt-10 lg:grid-cols-[1fr_340px]"><div><h1 className="text-2xl">DELIVERY <span className="font-semibold">INFORMATION</span></h1><div className="mt-7 grid gap-3 sm:grid-cols-2"><input required name="firstName" defaultValue={user?.name?.split(' ')[0]} placeholder="First name" className="border p-3" /><input required name="lastName" placeholder="Last name" className="border p-3" /><input required type="email" name="email" defaultValue={user?.email} placeholder="Email address" className="border p-3 sm:col-span-2" /><input required name="street" placeholder="Street" className="border p-3 sm:col-span-2" /><input required name="city" placeholder="City" className="border p-3" /><input required name="state" placeholder="State" className="border p-3" /><input required name="zip" placeholder="PIN code" className="border p-3" /><input required name="phone" placeholder="Phone" className="border p-3" /></div><h2 className="mt-10 text-xl">PAYMENT METHOD</h2><div className="mt-4 flex gap-3"><button type="button" onClick={() => setPayment('COD')} className={`border px-5 py-3 text-sm ${payment === 'COD' ? 'border-black bg-black text-white' : ''}`}>CASH ON DELIVERY</button><button type="button" onClick={() => setPayment('ONLINE')} className={`border px-5 py-3 text-sm ${payment === 'ONLINE' ? 'border-black bg-black text-white' : ''}`}>ONLINE (DEMO)</button></div></div><aside className="h-fit bg-gray-50 p-6"><h2 className="text-xl">ORDER TOTAL</h2><div className="mt-5 space-y-3 border-y py-4 text-sm"><p className="flex justify-between"><span>Items ({cartItems.length})</span><span>₹{subtotal}</span></p><p className="flex justify-between"><span>Shipping</span><span>₹{subtotal ? 10 : 0}</span></p></div><p className="flex justify-between py-4 font-semibold"><span>Total</span><span>₹{subtotal + (subtotal ? 10 : 0)}</span></p><button className="w-full bg-black py-3 text-sm text-white">PLACE ORDER</button></aside></form>
  )
}
export default PlaceOrder
